name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - run: cd mods; zip release.zip *; mv release.zip ..; cd ..
    - run: tar cf serversyncmods.tar.xz ./mods/*
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip,serversyncmods.tar.xz"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
