name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        path: mods
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
