name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - run: zip release.zip ./mods/* -j
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
