name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - run: cd mods; zip release.zip *; mv release.zip ..; cd ..
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
